### ISSUE TITLE
Beim Anklicken von Links auf der "Spieltermine"-Seite bewegen sich Tabellen zur Seite

### ISSUE THREAD

**Issue by fkaelberer** [fkaelberer/bvbbpp#14]
Der Link wird hingegen nicht verfolgt. 
(Google Chrome)

**Comment by martingruhn** [comment]
Scheint, als würde das auch mit #10 gelöst werden: Jedenfalls springt die Tabelle nicht mehr, wenn man die Calender-/Doodle-Icons entfernt (war ein schneller Test).
